### development version

version: "2"

services:
  mongo:
    container_name: blog.mongo
    image: mongo
    restart: always
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - 27017:27017

  node:
    container_name: blog.node
    build: .
    restart: always
    volumes:
      - "./src:/app/src"
    links:
      - mongo
    env_file:
      - .env.development
    ports:
      - 5000:5000
